import os
import re
import zipfile
import tempfile
from pathlib import Path


def parse_files_from_output(code_output: str) -> dict:
    files = {}
    pattern = r'#\s*FILE:\s*([^\n]+)\n(.*?)(?=\n#\s*FILE:|\Z)'
    matches = re.findall(pattern, code_output, re.DOTALL)

    for filepath, content in matches:
        filepath = filepath.strip()
        content = content.strip()
        content = re.sub(r'^```[\w]*\n?', '', content)
        content = re.sub(r'\n?```$', '', content)
        content = content.strip()
        files[filepath] = content

    return files


def ensure_readme(
    files: dict,
    qa_summary: str,
    goal_analysis: str,
    chosen_stack: str = "crewai"
) -> dict:
    has_readme = any(
        k.lower() == 'readme.md' or k.lower().endswith('/readme.md')
        for k in files.keys()
    )

    if not has_readme:
        stack_line = f"- Generated by DevCrew — AI-powered project builder"
        if chosen_stack.lower() == "crewai":
            built_with = "CrewAI + Groq"
        elif chosen_stack.lower() == "langchain":
            built_with = "LangChain + Groq"
        elif chosen_stack.lower() == "nodejs":
            built_with = "Node.js + Groq"
        elif chosen_stack.lower() == "autogen":
            built_with = "AutoGen + Groq"
        else:
            built_with = f"{chosen_stack} + Groq"

        files['README.md'] = f"""# DevCrew Generated Project

## Project Summary
{goal_analysis}

## Setup Instructions
1. Clone or extract this project folder
2. Install dependencies as listed below
3. Copy `.env.example` to `.env` and fill in your credentials
4. Run the project as described in the How to Run section

## Credentials
- Check `.env.example` for all required environment variables
- Each variable has a comment explaining where to get it

## How to Run
- Follow the setup instructions above
- Refer to individual file comments for more detail

## Built With
{stack_line}
- Powered by {built_with}

---
## QA Summary
{qa_summary}

---
*This project was generated by DevCrew. Replace all placeholder values before running.*
"""
    else:
        for key in list(files.keys()):
            if key.lower() == 'readme.md' or key.lower().endswith('/readme.md'):
                content = files[key]
                if "crewai + groq" in content.lower() and chosen_stack.lower() != "crewai":
                    if chosen_stack.lower() == "langchain":
                        files[key] = content.replace(
                            "CrewAI + Groq", "LangChain + Groq"
                        ).replace(
                            "crewai + groq", "LangChain + Groq"
                        )
                    else:
                        files[key] = content.replace(
                            "CrewAI + Groq", f"{chosen_stack} + Groq"
                        )
                break

    return files


def ensure_env_example(files: dict, chosen_stack: str = "crewai") -> dict:
    has_env = any(
        k == '.env.example' or k.endswith('/.env.example')
        for k in files.keys()
    )

    if not has_env:
        if chosen_stack.lower() == "crewai":
            env_content = """# Copy this file to .env and fill in your values

# Groq API Key — get your free key at https://console.groq.com
GROQ_API_KEY=your_groq_api_key_here

# Model to use — llama-3.1-8b-instant is free and fast
MODEL_NAME=llama-3.1-8b-instant
"""
        elif chosen_stack.lower() == "langchain":
            env_content = """# Copy this file to .env and fill in your values

# Groq API Key — get your free key at https://console.groq.com
GROQ_API_KEY=your_groq_api_key_here

# Model to use
MODEL_NAME=llama-3.1-8b-instant

# Server port (optional)
PORT=3000
"""
        elif chosen_stack.lower() == "nodejs":
            env_content = """# Copy this file to .env and fill in your values

# Groq API Key — get your free key at https://console.groq.com
GROQ_API_KEY=your_groq_api_key_here

# Model to use
MODEL_NAME=llama-3.1-8b-instant

# Server port
PORT=3000
"""
        else:
            env_content = """# Copy this file to .env and fill in your values

# Groq API Key — get your free key at https://console.groq.com
GROQ_API_KEY=your_groq_api_key_here

# Model name
MODEL_NAME=llama-3.1-8b-instant
"""
        files['.env.example'] = env_content
    else:
        for key in list(files.keys()):
            if key == '.env.example' or key.endswith('/.env.example'):
                content = files[key]
                if len(content.strip()) < 50 or 'your-service.com' in content:
                    if chosen_stack.lower() == "crewai":
                        files[key] = """# Copy this file to .env and fill in your values

# Groq API Key — get your free key at https://console.groq.com
GROQ_API_KEY=your_groq_api_key_here

# Model to use — llama-3.1-8b-instant is free and fast
MODEL_NAME=llama-3.1-8b-instant
"""
                    else:
                        files[key] = f"""# Copy this file to .env and fill in your values

# Groq API Key — get your free key at https://console.groq.com
GROQ_API_KEY=your_groq_api_key_here

# Model to use
MODEL_NAME=llama-3.1-8b-instant

# App port
PORT=3000
"""
                break

    return files


def create_zip(
    code_output: str,
    qa_summary: str,
    goal_analysis: str,
    project_name: str = "devcrew_project",
    chosen_stack: str = "crewai"
) -> str:
    files = parse_files_from_output(code_output)

    if not files:
        files['README.md'] = (
            f"# {project_name}\n\n"
            f"## Project Summary\n{goal_analysis}\n\n"
            f"## Note\n"
            f"The code generation did not produce parseable files. "
            f"Please try again.\n\n"
            f"## QA Summary\n{qa_summary}"
        )

    files = ensure_readme(files, qa_summary, goal_analysis, chosen_stack)
    files = ensure_env_example(files, chosen_stack)

    tmp_dir = tempfile.mkdtemp()
    zip_path = os.path.join(tmp_dir, f"{project_name}.zip")

    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for filepath, content in files.items():
            arcname = os.path.join(project_name, filepath)
            arcname = arcname.replace('\\', '/')
            zf.writestr(arcname, content)

        build_log = f"""# DevCrew Build Log

## Stack Used
{chosen_stack}

## QA Summary
{qa_summary}

## Files Generated
{chr(10).join(f'- {f}' for f in files.keys())}

## Built With
DevCrew — AI-powered project builder
Powered by CrewAI + Groq
"""
        zf.writestr(
            os.path.join(project_name, 'DEVCREW_BUILD_LOG.md'),
            build_log
        )

    return zip_path


def get_project_name(goal_analysis: str) -> str:
    lines = goal_analysis.split('\n')
    for line in lines:
        if 'project summary' in line.lower() or 'project:' in line.lower():
            clean = re.sub(r'[^a-zA-Z0-9\s]', '', line)
            words = clean.strip().split()[:4]
            if words:
                return '_'.join(words).lower()
    return 'devcrew_project'



# import os
# import re
# import zipfile
# import tempfile
# from pathlib import Path


# def parse_files_from_output(code_output: str) -> dict:
#     """
#     Parses the coder agent's output and extracts individual files.
#     Each file must start with a comment: # FILE: path/to/filename.ext
#     Returns a dict of {filepath: file_contents}
#     """
#     files = {}
    
#     pattern = r'#\s*FILE:\s*([^\n]+)\n(.*?)(?=\n#\s*FILE:|\Z)'
#     matches = re.findall(pattern, code_output, re.DOTALL)
    
#     for filepath, content in matches:
#         filepath = filepath.strip()
#         content = content.strip()
        
#         content = re.sub(r'^```[\w]*\n?', '', content)
#         content = re.sub(r'\n?```$', '', content)
#         content = content.strip()
        
#         files[filepath] = content
    
#     return files


# def ensure_readme(files: dict, qa_summary: str, goal_analysis: str) -> dict:
#     """
#     Makes sure README.md exists in the output.
#     If coder didn't generate one, creates a default one.
#     """
#     has_readme = any(
#         k.lower() == 'readme.md' or k.lower().endswith('/readme.md')
#         for k in files.keys()
#     )
    
#     if not has_readme:
#         files['README.md'] = f"""# DevCrew Generated Project

# ## Project Summary
# {goal_analysis}

# ## Setup Instructions
# 1. Clone or extract this project folder
# 2. Install dependencies as listed below
# 3. Copy `.env.example` to `.env` and fill in your credentials
# 4. Run the project as described in the How to Run section

# ## Credentials
# - Check `.env.example` for all required environment variables
# - Each variable has a comment explaining where to get it

# ## How to Run
# - Follow the setup instructions above
# - Refer to individual file comments for more detail

# ## Built With
# - Generated by DevCrew — AI-powered project builder
# - Powered by CrewAI + Groq

# ---
# ## QA Summary
# {qa_summary}

# ---
# *This project was generated by DevCrew. Replace all placeholder values before running.*
# """
#     return files


# def ensure_env_example(files: dict) -> dict:
#     """
#     Makes sure .env.example exists.
#     If not generated by coder, creates a default one.
#     """
#     has_env = any(
#         k == '.env.example' or k.endswith('/.env.example')
#         for k in files.keys()
#     )
    
#     if not has_env:
#         files['.env.example'] = """# Copy this file to .env and fill in your values

# # Example:
# # API_KEY=your_api_key_here
# # Get your API key from: https://your-service.com/api-keys
# """
#     return files


# def create_zip(
#     code_output: str,
#     qa_summary: str,
#     goal_analysis: str,
#     project_name: str = "devcrew_project"
# ) -> str:
#     """
#     Takes the coder's raw output, parses all files,
#     and packages them into a ZIP file.
#     Returns the path to the created ZIP file.
#     """
    
#     files = parse_files_from_output(code_output)
    
#     if not files:
#         files['README.md'] = (
#             f"# {project_name}\n\n"
#             f"## Project Summary\n{goal_analysis}\n\n"
#             f"## Note\n"
#             f"The code generation did not produce parseable files. "
#             f"Please review the QA summary below and try again.\n\n"
#             f"## QA Summary\n{qa_summary}"
#         )
    
#     files = ensure_readme(files, qa_summary, goal_analysis)
#     files = ensure_env_example(files)
    
#     tmp_dir = tempfile.mkdtemp()
#     zip_path = os.path.join(tmp_dir, f"{project_name}.zip")
    
#     with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
#         for filepath, content in files.items():
#             arcname = os.path.join(project_name, filepath)
#             arcname = arcname.replace('\\', '/')
#             zf.writestr(arcname, content)
        
#         build_log = f"""# DevCrew Build Log

# ## QA Summary
# {qa_summary}

# ## Files Generated
# {chr(10).join(f'- {f}' for f in files.keys())}

# ## Built With
# DevCrew — AI-powered project builder
# Powered by CrewAI + Groq
# """
#         zf.writestr(
#             os.path.join(project_name, 'DEVCREW_BUILD_LOG.md'),
#             build_log
#         )
    
#     return zip_path


# def get_project_name(goal_analysis: str) -> str:
#     """
#     Extracts a clean project name from the goal analysis.
#     Falls back to 'devcrew_project' if nothing found.
#     """
#     lines = goal_analysis.split('\n')
#     for line in lines:
#         if 'project summary' in line.lower() or 'project:' in line.lower():
#             clean = re.sub(r'[^a-zA-Z0-9\s]', '', line)
#             words = clean.strip().split()[:4]
#             if words:
#                 return '_'.join(words).lower()
    
#     return 'devcrew_project'